'use strict';
/* more starter templates */
const T=(tree,css,json='{}',events=[],js='')=>({tree,css,json,events,js});
const R=(sel,body)=>({sel,media:'',body});
const trow=(tag,cells)=>n('tr',{children:cells.map(c=>n(tag,{text:c}))});
const plan=(name,price,items)=>n('article',{attrs:{class:'plan'},children:[n('h2',{text:name}),n('p',{text:price,attrs:{class:'price'}}),n('ul',{children:items.map(i=>n('li',{text:i}))}),n('a',{text:'Choose '+name,attrs:{href:'#'}})]});
const BODY=R('body','font-family: system-ui, sans-serif;\nmargin: 0;');
Object.assign(TEMPLATES,{
landing:()=>T([n('header',{attrs:{class:'hero'},children:[n('h1',{text:'Launch faster with Acme'}),n('p',{text:'A short promise about what your product does.'}),n('a',{text:'Get started',attrs:{href:'#',class:'cta'}})]}),n('section',{attrs:{class:'features'},children:[n('h2',{text:'Why people choose it'}),n('ul',{children:[n('li',{text:'Simple to set up'}),n('li',{text:'Works on every device'}),n('li',{text:'Friendly support'})]})]}),n('footer',{text:'© Acme'})],[BODY,R('.hero','padding: 72px 24px;\ntext-align: center;\nbackground: #e8eefc;'),R('.cta','display: inline-block;\npadding: 10px 20px;\nbackground: #2a56d6;\ncolor: #fff;\nborder-radius: 6px;\ntext-decoration: none;'),R('.features','max-width: 640px;\nmargin: 40px auto;\npadding: 0 16px;'),R('footer','text-align: center;\npadding: 24px;\ncolor: #667;')]),
form:()=>{const c=CMPS['Contact form']();return T([n('main',{attrs:{class:'page'},children:[n('h1',{text:'Contact us'}),...c.nodes]})],[BODY,R('.page','max-width: 420px;\nmargin: 40px auto;'),...c.css.map(r=>R(r.sel,r.body))])},
business:()=>{const nv=CMPS.Navbar(),hr=CMPS.Hero();return T([...nv.nodes,...hr.nodes,n('section',{attrs:{class:'services'},children:[n('h2',{text:'Our services'}),n('ul',{children:['Consulting','Installation','Support'].map(t=>n('li',{text:t}))})]}),n('footer',{text:'© Your Company'})],[BODY,...nv.css.map(r=>R(r.sel,r.body)),...hr.css.map(r=>R(r.sel,r.body)),R('.services','max-width: 640px;\nmargin: 40px auto;\npadding: 0 16px;'),R('footer','text-align: center;\npadding: 24px;')])},
pricing:()=>T([n('main',{attrs:{class:'plans'},children:[plan('Basic','$9',['1 project','Email support']),plan('Pro','$29',['10 projects','Priority support']),plan('Team','$79',['Unlimited projects','Phone support'])]})],[BODY,R('.plans','display: flex;\ngap: 16px;\njustify-content: center;\nflex-wrap: wrap;\npadding: 40px 16px;'),R('.plan','border: 1px solid #c8d0da;\nborder-radius: 10px;\npadding: 20px;\nwidth: 220px;'),R('.price','font-size: 2rem;\nfont-weight: 700;')]),
dashboard:()=>T([n('header',{children:[n('h1',{text:'Sales dashboard'})]}),n('section',{attrs:{class:'stats'},children:[['Orders','128'],['Revenue','$12,400'],['Returns','3']].map(([l,v])=>n('div',{attrs:{class:'stat'},children:[n('strong',{text:v}),n('span',{text:l})]}))}),n('table',{children:[n('thead',{children:[trow('th',['Customer','Item','Total'])]}),n('tbody',{children:[trow('td',['Ada','Box truck','$18,000']),trow('td',['Grace','Cargo van','$9,500'])]})]})],[BODY,R('header','padding: 16px 24px;\nbackground: #1c2631;\ncolor: #fff;'),R('.stats','display: flex;\ngap: 16px;\npadding: 24px;'),R('.stat','display: grid;\nborder: 1px solid #c8d0da;\nborder-radius: 8px;\npadding: 16px;\nmin-width: 120px;'),R('table','margin: 0 24px;\nborder-collapse: collapse;'),R('th, td','border-bottom: 1px solid #c8d0da;\npadding: 8px 16px;\ntext-align: left;')]),
table:()=>T([n('main',{attrs:{class:'page'},children:[n('h1',{text:'Inventory'}),n('table',{children:[n('thead',{children:[trow('th',['Unit','Type','Price'])]}),n('tbody',{children:[trow('td',['101','Box truck','$18,000']),trow('td',['102','Flatbed','$22,500']),trow('td',['103','Cargo van','$9,500'])]})]})]})],[BODY,R('.page','max-width: 640px;\nmargin: 40px auto;'),R('table','width: 100%;\nborder-collapse: collapse;'),R('th, td','border-bottom: 1px solid #c8d0da;\npadding: 8px;\ntext-align: left;')]),
todo:()=>T([n('main',{attrs:{class:'page'},children:[n('h1',{text:'To-do list'}),n('label',{text:'New task',attrs:{for:'task'}}),n('input',{attrs:{id:'task',type:'text'}}),n('button',{text:'Add task',attrs:{id:'addtask'}}),n('ul',{attrs:{id:'list'}})]})],[BODY,R('.page','max-width: 420px;\nmargin: 40px auto;'),R('li','cursor: pointer;\npadding: 4px 0;')],'{}',[],"document.getElementById('addtask').addEventListener('click', () => {\n  const input = document.getElementById('task');\n  if (!input.value.trim()) return;\n  const li = document.createElement('li');\n  li.textContent = input.value;\n  li.addEventListener('click', () => li.remove());\n  document.getElementById('list').append(li);\n  input.value = '';\n});"),
timer:()=>T([n('main',{attrs:{class:'page'},children:[n('h1',{text:'Timer'}),n('p',{text:'0',attrs:{id:'time'}}),n('button',{text:'Start',attrs:{id:'start'}}),n('button',{text:'Stop',attrs:{id:'stop'}})]})],[BODY,R('.page','text-align: center;\nmargin-top: 48px;'),R('#time','font-size: 4rem;\nmargin: 0.5rem;')],'{}',[],"let seconds = 0;\nlet id = null;\ndocument.getElementById('start').addEventListener('click', () => {\n  if (id) return;\n  id = setInterval(() => {\n    seconds++;\n    document.getElementById('time').textContent = seconds;\n  }, 1000);\n});\ndocument.getElementById('stop').addEventListener('click', () => {\n  clearInterval(id);\n  id = null;\n});")});
/* more templates */
const btn=(t,id)=>n('button',{text:t,attrs:{id}});
const PG=R('.page','max-width: 480px;\nmargin: 40px auto;\npadding: 0 16px;');
Object.assign(TEMPLATES,{
quiz:()=>T([n('main',{attrs:{class:'page'},children:[n('h1',{text:'Quick quiz'}),n('p',{text:'What is 2 + 2?'}),btn('3','a3'),btn('4','a4'),btn('5','a5'),n('p',{attrs:{id:'result'}})]})],[BODY,PG],'{}',[],"const answers = { a3: false, a4: true, a5: false };\nObject.entries(answers).forEach(([id, ok]) => {\n  document.getElementById(id).addEventListener('click', () => {\n    document.getElementById('result').textContent = ok ? 'Correct!' : 'Not quite. Try again.';\n  });\n});"),
calculator:()=>T([n('main',{attrs:{class:'page'},children:[n('h1',{text:'Calculator'}),n('label',{text:'First number',attrs:{for:'a'}}),n('input',{attrs:{id:'a',type:'number'}}),n('label',{text:'Second number',attrs:{for:'b'}}),n('input',{attrs:{id:'b',type:'number'}}),btn('+','add'),btn('−','sub'),btn('×','mul'),btn('÷','div'),n('p',{text:'0',attrs:{id:'out'}})]})],[BODY,PG,R('#out','font-size: 2rem;')],'{}',[],"const num = (id) => Number(document.getElementById(id).value);\nconst show = (v) => {\n  document.getElementById('out').textContent = Number.isFinite(v) ? v : 'Not a number';\n};\ndocument.getElementById('add').addEventListener('click', () => show(num('a') + num('b')));\ndocument.getElementById('sub').addEventListener('click', () => show(num('a') - num('b')));\ndocument.getElementById('mul').addEventListener('click', () => show(num('a') * num('b')));\ndocument.getElementById('div').addEventListener('click', () => show(num('a') / num('b')));"),
services:()=>{const nv=CMPS.Navbar(),cs=['Consulting','Installation','Support'].map(t=>{const c=CMPS.Card();c.nodes[0].children[0].text=t;return c});return T([...nv.nodes,n('main',{attrs:{class:'cards'},children:[n('h1',{text:'Services'}),...cs.map(c=>c.nodes[0])]})],[BODY,...nv.css.map(r=>R(r.sel,r.body)),...CMPS.Card().css.map(r=>R(r.sel,r.body)),R('.cards','display: flex;\nflex-wrap: wrap;\ngap: 16px;\npadding: 24px;'),R('.cards h1','width: 100%;')])},
product:()=>T([n('main',{attrs:{class:'page'},children:[n('h1',{text:'Folding Camp Chair'}),n('p',{text:'$49',attrs:{class:'price'}}),n('p',{text:'Lightweight steel frame. Holds up to 250 lb. Packs into its own carry bag.'}),btn('Add to cart','buy'),n('p',{attrs:{id:'msg'}})]})],[BODY,PG,R('.price','font-size: 2rem;\nfont-weight: 700;')],'{}',[{target:'buy',event:'click',action:'text',value:'Added to cart',to:'msg'}]),
inventory:()=>T([n('main',{attrs:{class:'page'},children:[n('h1',{text:'Inventory'}),n('label',{text:'Unit',attrs:{for:'unit'}}),n('input',{attrs:{id:'unit',type:'text'}}),n('label',{text:'Price',attrs:{for:'price'}}),n('input',{attrs:{id:'price',type:'text'}}),btn('Add unit','addrow'),n('table',{children:[n('thead',{children:[trow('th',['Unit','Price'])]}),n('tbody',{attrs:{id:'rows'},children:[trow('td',['101','$18,000'])]})]})]})],[BODY,PG,R('table','width: 100%;\nborder-collapse: collapse;\nmargin-top: 16px;'),R('th, td','border-bottom: 1px solid #c8d0da;\npadding: 8px;\ntext-align: left;')],'{}',[],"document.getElementById('addrow').addEventListener('click', () => {\n  const unit = document.getElementById('unit');\n  const price = document.getElementById('price');\n  if (!unit.value.trim()) return;\n  const tr = document.createElement('tr');\n  [unit.value, price.value].forEach((v) => {\n    const td = document.createElement('td');\n    td.textContent = v;\n    tr.append(td);\n  });\n  document.getElementById('rows').append(tr);\n  unit.value = '';\n  price.value = '';\n});"),
crm:()=>T([n('main',{attrs:{class:'page'},children:[n('h1',{text:'Contacts'}),n('table',{children:[n('thead',{children:[trow('th',['Name','Company','Status'])]}),n('tbody',{children:[trow('td',['Ada Lovelace','Analytical Co','Lead']),trow('td',['Grace Hopper','Navy Yard LLC','Customer']),trow('td',['Alan Turing','Bletchley Inc','Follow up'])]})]})]})],[BODY,R('.page','max-width: 720px;\nmargin: 40px auto;\npadding: 0 16px;'),R('table','width: 100%;\nborder-collapse: collapse;'),R('th, td','border-bottom: 1px solid #c8d0da;\npadding: 8px;\ntext-align: left;')])});
/* admin panel */
Object.assign(TEMPLATES,{admin:()=>T([n('div',{attrs:{class:'shell'},children:[n('nav',{attrs:{class:'side'},children:[n('a',{text:'Overview',attrs:{href:'#'}}),n('a',{text:'Users',attrs:{href:'#'}}),n('a',{text:'Settings',attrs:{href:'#'}})]}),n('main',{children:[n('h1',{text:'Admin'}),n('p',{text:'Welcome back.'}),n('table',{children:[n('thead',{children:[trow('th',['User','Role'])]}),n('tbody',{children:[trow('td',['ada','Owner']),trow('td',['grace','Editor'])]})]})]})]})],[BODY,R('.shell','display: grid;\ngrid-template-columns: 200px 1fr;\nmin-height: 100vh;'),{sel:'.shell',media:'(max-width: 600px)',body:'grid-template-columns: 1fr;'},R('.side','display: grid;\nalign-content: start;\ngap: 8px;\npadding: 16px;\nbackground: #1c2631;'),R('.side a','color: #fff;\ntext-decoration: none;'),R('main','padding: 24px;'),R('th, td','text-align: left;\npadding: 8px 16px;\nborder-bottom: 1px solid #c8d0da;')])});
